backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}

  - name: "musicalwork"
    label: "Musical Works"
    label_singular: "Musical Work"
    folder: "content/data/musicalwork"
    extension: "json"
    format: "json"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Title (Ar)", name: "title_ar", widget: "datetime"}
      - {label: "Alternate Titles", name: "alternate_titles", widget: "list", allow_add: true,
            field: {label: "Alternate Title", name: "alt_title", widget: "string"}
         }
      - {label: "Lyrics", name: "lyrics", widget: "text"}
      - {label: "Genre", name: "genre", widget: "relation",
         collection: "genre", 
         searchFields: ["name"],
         valueField: "name",
         displayFields: ["name"],
         multiple: false
         }
      - {label: "Contributors",
         name: "contributors",
         widget: "list",
         allow_add: true,
         fields: [
            {name: "contributor_role",
             label: "Role",
             widget: "select",
             options: ["Composer", "Writer"]
            },
            {name: "contributor",
             label: "Contributor",
             widget: "relation",
             collection: "agent", 
             searchFields: ["name"],
             valueField: "name",
             displayFields: ["name"]}
             ]
         }
         
  - name: "genre"
    label: "Genres"
    label_singular: "Genre"
    folder: "content/data/genre"
    extension: "json"
    format: "json"
    create: true
    identifier_field: "name"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Name (Ar)", name: "name_ar", widget: "string"}

  - name: "agent"
    label: "Agents"
    label_singular: "Agent"
    folder: "content/data/agent"
    extension: "json"
    format: "json"
    create: true
    identifier_field: "name"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Name (Ar)", name: "name_ar", widget: "datetime"}
      - {label: "Alternate Names", name: "alternate_names", widget: "list", allow_add: true,
            field: {label: "Alternate Name", name: "alt_name", widget: "string"}
         }
      - {name: "usual_role",
         label: "Usual Role",
         widget: "select",
         options: ["Artist", "Composer", "Conductor", "Musician", "Performer", "Performing Group", "Recording Engineer", "Vocalist", "Writer"]
         }
         
  - name: "release"
    label: "Releases"
    label_singular: "Release"
    folder: "content/data/release"
    extension: "json"
    format: "json"
    create: true
    fields:
      - {label: "Title of Release", name: "title", widget: "string"}
      - {label: "Label", name: "label", widget: "string"}
      - {label: "Catalogue Numbers", label_singular: "Catalogue Number", name: "catalogue_numbers", widget: "list", allow_add: true,
            field: {label: "Catalogue Number", name: "catalogue_number", widget: "string"}
         }
      - {label: "Release Type", name: "release_type", widget: "select", default: "Commercial", options: ["Commercial", "Prova"]}
      - {label: "Record Count", name: "record_count", widget: "number", default: 1, valueType: "int"}
      - {label: "Media Type",
         name: "media_type",
         widget: "select",
         default: 1,
         options: ["Shellac disc [10 inch]",
                   "Shellac disc [12 inch]",
                   "Vinyl recording",
                   "Wax Cylinder"]
                   }
      - {label: "Artist", name: "artist", widget: "relation",
         collection: "agent", 
         searchFields: ["name"],
         valueField: "name",
         displayFields: ["name"],
         multiple: true
         }
         
  - name: "track"
    label: "Tracks"
    label_singular: "Track"
    folder: "content/data/track"
    extension: "json"
    format: "json"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Record Side", name: "record_side", widget: "string"}
      - {label: "Track Number", name: "track_number", multiple: true, widget: "string"}
      - {label: "Musical Work",
         name: "work",
         widget: "relation",
         collection: "musicalwork", 
         searchFields: ["genre", "name"],
         valueField: "name",
         displayFields: ["genre", "name"]
         }
      - {label: "Artists and Contributors",
         name: "contributors",
         widget: "list",
         allow_add: true,
         fields: [
            {name: "contributor_role",
             label: "Role",
             widget: "select",
             options: ["Artist", "Composer", "Conductor", "Musician", "Performer", "Performing Group", "Recording Engineer", "Vocalist", "Writer"]
            },
            {name: "contributor",
             label: "Contributor",
             widget: "relation",
             collection: "agent", 
             searchFields: ["name"],
             valueField: "name",
             displayFields: ["name"]}
             ]
         }
         
